SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS-- List columns in all tables whose name is like 'TableName'
WHERE  TABLE_SCHEMA = 'alx_book_store'
AND TABLE_NAME = 'Books';
